version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Install HTML proofer gem
          command: gem install html-proofer

      - run:
          name: Run HTML proofer
          command: htmlproofer --disable-external .
